import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  ALERT,
  HEARTBEAT_ISSUE,
  RECORD_PATTERN,
  ROUTINES,
  RUN_ALLOWANCE_MS,
  DST_SHIFT_MS,
  WORKFLOW_FILE,
  buildAlertIssueBody,
  dueFire,
  evaluateHeartbeat,
  lastScheduledFire,
  parseRecords,
  readHeartbeat,
  readJudgeFrom,
  runWatchdog,
} from "../routine-heartbeat.mjs";
import { ALERT_ASSIGNEE, ALERT_LOOKUP_LABEL } from "../lib/alert-issue.mjs";

import { makeFetchMock } from "./helpers.mjs";

const REPO_ROOT = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "..",
);
const WORKFLOW = join(REPO_ROOT, ".github", "workflows", WORKFLOW_FILE);
const ROUTINES_DOC = join(REPO_ROOT, "docs", "ci-cd", "routines.md");
const ALERT_ROUTING = join(
  REPO_ROOT,
  "docs",
  "internal",
  "ops",
  "ALERT_ROUTING.md",
);
const AGENT_INFRA = join(REPO_ROOT, "docs", "ci-cd", "agent-infra.md");

const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;
// Wednesday 2026-10-07, 19:20 UTC: the workflow's daily slot.
const NOW = Date.parse("2026-10-07T19:20:00Z");
const LONG_AGO = Date.parse("2026-09-01T00:00:00Z");

const bySlug = Object.fromEntries(
  ROUTINES.map((routine) => [routine.slug, routine]),
);

function record(
  slug,
  outcome,
  at,
  { author = "OWNER", reason = "", fenced = false } = {},
) {
  const lines = [`routine-run: v1 routine=${slug} outcome=${outcome}`];
  if (reason) lines.push(reason);
  const body = fenced
    ? ["```text", ...lines, "```"].join("\n")
    : lines.join("\n");
  return {
    author_association: author,
    created_at: new Date(at).toISOString(),
    body: `${body}\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_`,
    html_url: `https://github.com/o/r/issues/${HEARTBEAT_ISSUE}#issuecomment-${at}`,
  };
}

/** A done record an hour after every routine's due fire. */
function allDone(now = NOW) {
  return ROUTINES.map((routine) =>
    record(routine.slug, "done", dueFire(routine, now) + HOUR),
  );
}

describe("the schedule", () => {
  it("finds a daily routine's fire today once it has passed, and yesterday's before", () => {
    const hygiene = bySlug["hygiene-scan"];
    assert.equal(
      lastScheduledFire(hygiene, NOW),
      Date.parse("2026-10-07T03:07:00Z"),
    );
    assert.equal(
      lastScheduledFire(hygiene, Date.parse("2026-10-07T03:06:00Z")),
      Date.parse("2026-10-06T03:07:00Z"),
    );
    assert.equal(
      lastScheduledFire(hygiene, Date.parse("2026-10-07T03:07:00Z")),
      Date.parse("2026-10-07T03:07:00Z"),
    );
  });

  it("finds a weekly routine's fire on its weekday, across a month boundary", () => {
    // Curator is Friday 12:07 UTC; 2026-10-07 is a Wednesday.
    assert.equal(
      lastScheduledFire(bySlug["issue-curator"], NOW),
      Date.parse("2026-10-02T12:07:00Z"),
    );
    // PR Follow-ups is Monday 11:07 UTC; from Thursday 2026-10-01 that is 2026-09-28.
    assert.equal(
      lastScheduledFire(
        bySlug["pr-followups"],
        Date.parse("2026-10-01T00:00:00Z"),
      ),
      Date.parse("2026-09-28T11:07:00Z"),
    );
    // Docs Upkeep on its own Wednesday: before 11:07 it is the previous week's.
    assert.equal(
      lastScheduledFire(
        bySlug["docs-upkeep"],
        Date.parse("2026-10-07T11:00:00Z"),
      ),
      Date.parse("2026-09-30T11:07:00Z"),
    );
  });

  it("judges the latest fire that has had its slack and run allowance", () => {
    const triage = bySlug["issue-triage"];
    // 13:07 + 1h + 4h = 18:07: before it, a run judges yesterday's triage.
    assert.equal(
      dueFire(triage, Date.parse("2026-10-07T18:00:00Z")),
      Date.parse("2026-10-06T13:07:00Z"),
    );
    assert.equal(dueFire(triage, NOW), Date.parse("2026-10-07T13:07:00Z"));
  });

  it("mirrors the routines' stored schedules (list_triggers, 2026-09-30)", () => {
    const cron = ({ minute, hour, weekday }) =>
      `${minute} ${hour} * * ${weekday ?? "*"}`;
    assert.deepEqual(
      Object.fromEntries(ROUTINES.map((r) => [r.slug, cron(r)])),
      {
        "issue-curator": "7 12 * * 5",
        "issue-triage": "7 13 * * *",
        "pr-followups": "7 11 * * 1",
        "docs-upkeep": "7 11 * * 3",
        "hygiene-scan": "7 3 * * *",
      },
    );
  });
});

describe("parseRecords", () => {
  it("reads a record in a code fence, with the next line as its reason", () => {
    const [parsed] = parseRecords([
      record("hygiene-scan", "stopped", NOW, {
        fenced: true,
        reason: "sandbox bringup failed",
      }),
    ]);
    assert.equal(parsed.routine, "hygiene-scan");
    assert.equal(parsed.outcome, "stopped");
    assert.equal(parsed.reason, "sandbox bringup failed");
    assert.equal(parsed.createdAt, NOW);
  });

  it("ignores comments from anyone but the owner, since the repo is public", () => {
    for (const author of [
      "NONE",
      "CONTRIBUTOR",
      "COLLABORATOR",
      "MEMBER",
      null,
    ]) {
      assert.deepEqual(
        parseRecords([record("issue-triage", "done", NOW, { author })]),
        [],
        String(author),
      );
    }
  });

  it("ignores comments that carry no record, or a malformed one", () => {
    const comment = (body) => ({
      author_association: "OWNER",
      created_at: new Date(NOW).toISOString(),
      body,
    });
    assert.deepEqual(
      parseRecords([
        comment("Routine-state issue. Please pin it."),
        comment("routine-run: v2 routine=issue-triage outcome=done"),
        comment("routine-run: v1 routine=issue-triage outcome=finished"),
        comment("see routine-run: v1 routine=issue-triage outcome=done"),
        {
          ...comment("routine-run: v1 routine=issue-triage outcome=done"),
          created_at: "not a date",
        },
      ]),
      [],
    );
  });

  it("reads a record wrapped in inline code, a quote, a bullet or bold", () => {
    const comment = (body) => ({
      author_association: "OWNER",
      created_at: new Date(NOW).toISOString(),
      body,
    });
    const line = "routine-run: v1 routine=issue-triage outcome=done";
    for (const body of [
      `\`${line}\``,
      `> ${line}`,
      `- ${line}`,
      `* ${line}`,
      `**${line}**`,
      `> \`${line}\``,
    ]) {
      const parsed = parseRecords([comment(body)]);
      assert.equal(parsed.length, 1, body);
      assert.equal(parsed[0].outcome, "done", body);
    }
  });

  it("takes no reason from the attribution footer", () => {
    const [parsed] = parseRecords([
      record("issue-triage", "done", NOW, { fenced: true }),
    ]);
    assert.equal(parsed.reason, "");
  });

  it("returns records oldest first", () => {
    const parsed = parseRecords([
      record("issue-triage", "done", NOW),
      record("issue-triage", "stopped", NOW - HOUR),
    ]);
    assert.deepEqual(
      parsed.map((r) => r.outcome),
      ["stopped", "done"],
    );
  });
});

describe("evaluateHeartbeat", () => {
  const evaluate = (comments, { now = NOW, judgeFrom = LONG_AGO } = {}) =>
    evaluateHeartbeat({ records: parseRecords(comments), now, judgeFrom });

  it("passes when every routine's due fire has a done record", () => {
    const verdict = evaluate(allDone());
    assert.equal(verdict.ok, true);
    assert.deepEqual(
      verdict.routines.map((r) => r.status),
      ROUTINES.map(() => "done"),
    );
  });

  it("fails a routine with no record since its due fire: the 09-17 startup failure", () => {
    const comments = allDone().filter(
      (c) => !c.body.includes("routine=issue-triage"),
    );
    const verdict = evaluate(comments);
    assert.equal(verdict.ok, false);
    assert.deepEqual(
      verdict.failing.map((r) => r.slug),
      ["issue-triage"],
    );
    assert.match(
      verdict.reason,
      /Issue Triage: no run record since its 2026-10-07T13:07Z run/,
    );
  });

  it("fails a routine whose newest record says it stopped: the 09-30 bringup failure", () => {
    const hygiene = bySlug["hygiene-scan"];
    const comments = allDone().filter(
      (c) => !c.body.includes("routine=hygiene-scan"),
    );
    comments.push(
      record("hygiene-scan", "stopped", dueFire(hygiene, NOW) + HOUR, {
        reason: "port 54322 already in use",
      }),
    );
    const verdict = evaluate(comments);
    assert.equal(verdict.ok, false);
    assert.match(
      verdict.reason,
      /Hygiene Scan: its 2026-10-07T03:07Z run stopped \(port 54322 already in use\)/,
    );
  });

  it("lets the newest record in the window win, so a re-run clears a stopped one", () => {
    const hygiene = bySlug["hygiene-scan"];
    const fire = dueFire(hygiene, NOW);
    const comments = allDone().filter(
      (c) => !c.body.includes("routine=hygiene-scan"),
    );
    const stoppedThenDone = [
      ...comments,
      record("hygiene-scan", "stopped", fire + HOUR),
      record("hygiene-scan", "done", fire + 3 * HOUR),
    ];
    assert.equal(evaluate(stoppedThenDone).ok, true);
    const doneThenStopped = [
      ...comments,
      record("hygiene-scan", "done", fire + HOUR),
      record("hygiene-scan", "stopped", fire + 3 * HOUR),
    ];
    assert.equal(evaluate(doneThenStopped).ok, false);
  });

  it("does not count the previous run's record for this one", () => {
    const hygiene = bySlug["hygiene-scan"];
    const comments = allDone().filter(
      (c) => !c.body.includes("routine=hygiene-scan"),
    );
    comments.push(
      record("hygiene-scan", "done", dueFire(hygiene, NOW) - DAY + HOUR),
    );
    assert.deepEqual(
      evaluate(comments).failing.map((r) => r.slug),
      ["hygiene-scan"],
    );
  });

  it("accepts a fire up to an hour late, for daylight saving", () => {
    const comments = ROUTINES.map((routine) =>
      record(
        routine.slug,
        "done",
        dueFire(routine, NOW) + DST_SHIFT_MS + 10 * 60 * 1000,
      ),
    );
    assert.equal(evaluate(comments).ok, true);
  });

  it("doesn't let a manual run before the fire stand in for it", () => {
    // Issue Triage run by hand at 12:00, then its 13:07 fire dies at startup.
    const triage = bySlug["issue-triage"];
    const comments = allDone().filter(
      (c) => !c.body.includes("routine=issue-triage"),
    );
    comments.push(
      record("issue-triage", "done", dueFire(triage, NOW) - 67 * 60 * 1000),
    );
    assert.deepEqual(
      evaluate(comments).failing.map((r) => r.slug),
      ["issue-triage"],
    );
  });

  it("judges nothing whose fire predates the watch's first run", () => {
    const verdict = evaluate([], { judgeFrom: NOW - 2 * HOUR });
    assert.equal(verdict.ok, true);
    assert.deepEqual(
      verdict.routines.map((r) => r.status),
      ROUTINES.map(() => "not-judged"),
    );
  });

  it("starts judging each routine at its first fire after the watch's first run", () => {
    // First run Tuesday 2026-10-06 19:20: fires since then are judged
    // (Wednesday's Hygiene, Docs Upkeep and Triage), the rest not until they
    // next fire.
    const verdict = evaluate([], {
      judgeFrom: Date.parse("2026-10-06T19:20:00Z"),
    });
    const status = Object.fromEntries(
      verdict.routines.map((r) => [r.slug, r.status]),
    );
    assert.deepEqual(status, {
      "issue-curator": "not-judged",
      "issue-triage": "missing",
      "pr-followups": "not-judged",
      "docs-upkeep": "missing",
      "hygiene-scan": "missing",
    });
  });
});

describe("readJudgeFrom", () => {
  const runsRoute = (body, status = 200) => ({
    method: "GET",
    path: `/actions/workflows/${WORKFLOW_FILE}/runs`,
    status,
    body,
  });

  it("reads the oldest run on main from the last page", async () => {
    const { fetchImpl, calls } = makeFetchMock([
      {
        method: "GET",
        path: `/actions/workflows/${WORKFLOW_FILE}/runs`,
        body: (recorded) =>
          recorded.at(-1).url.includes("&page=3")
            ? {
                total_count: 3,
                workflow_runs: [{ created_at: "2026-10-01T18:20:05Z" }],
              }
            : {
                total_count: 3,
                workflow_runs: [{ created_at: "2026-10-03T18:20:05Z" }],
              },
      },
    ]);
    assert.equal(
      await readJudgeFrom({ token: "t", repo: "o/r", fetchImpl }),
      Date.parse("2026-10-01T18:20:05Z"),
    );
    assert.ok(calls.every((c) => c.url.includes("branch=main")));
  });

  it("uses the first page when there is one run", async () => {
    const { fetchImpl, calls } = makeFetchMock([
      runsRoute({
        total_count: 1,
        workflow_runs: [{ created_at: "2026-10-01T18:20:05Z" }],
      }),
    ]);
    assert.equal(
      await readJudgeFrom({ token: "t", repo: "o/r", fetchImpl }),
      Date.parse("2026-10-01T18:20:05Z"),
    );
    assert.equal(calls.length, 1);
  });

  it("stays inside GitHub's 1,000-result limit on a long history", async () => {
    const { fetchImpl, calls } = makeFetchMock([
      runsRoute({
        total_count: 2500,
        workflow_runs: [{ created_at: "2019-01-01T19:20:00Z" }],
      }),
    ]);
    assert.equal(
      await readJudgeFrom({ token: "t", repo: "o/r", fetchImpl }),
      Date.parse("2019-01-01T19:20:00Z"),
    );
    assert.match(calls.at(-1).url, /&page=1000$/);
  });

  it("returns null when the runs can't be read, or read as none", async () => {
    for (const route of [
      runsRoute({}, 403),
      runsRoute({ total_count: 0, workflow_runs: [] }),
      runsRoute({ message: "x" }),
    ]) {
      const { fetchImpl } = makeFetchMock([route]);
      assert.equal(
        await readJudgeFrom({ token: "t", repo: "o/r", fetchImpl }),
        null,
      );
    }
  });
});

describe("readHeartbeat", () => {
  const judgeFromRoute = {
    method: "GET",
    path: `/actions/workflows/${WORKFLOW_FILE}/runs`,
    body: {
      total_count: 1,
      workflow_runs: [{ created_at: "2026-09-01T00:00:00Z" }],
    },
  };

  it("reads the heartbeat issue's comments since the oldest due fire and judges them", async () => {
    const { fetchImpl, calls } = makeFetchMock([
      judgeFromRoute,
      {
        method: "GET",
        path: `/issues/${HEARTBEAT_ISSUE}/comments`,
        body: allDone(),
      },
    ]);
    const verdict = await readHeartbeat({
      token: "t",
      repo: "o/r",
      fetchImpl,
      now: NOW,
    });
    assert.equal(verdict.ok, true);
    const commentsCall = calls.find((c) => c.url.includes("/comments"));
    const since = Date.parse(
      new URL(commentsCall.url).searchParams.get("since"),
    );
    assert.equal(since, dueFire(bySlug["issue-curator"], NOW));
  });

  it("pages through a full page of comments", async () => {
    const filler = Array.from({ length: 100 }, () => ({
      author_association: "OWNER",
      created_at: new Date(NOW).toISOString(),
      body: "x",
    }));
    const { fetchImpl, calls } = makeFetchMock([
      judgeFromRoute,
      {
        method: "GET",
        path: `/issues/${HEARTBEAT_ISSUE}/comments`,
        body: (recorded) =>
          recorded.at(-1).url.includes("&page=1") ? filler : allDone(),
      },
    ]);
    const verdict = await readHeartbeat({
      token: "t",
      repo: "o/r",
      fetchImpl,
      now: NOW,
    });
    assert.equal(verdict.ok, true);
    assert.equal(calls.filter((c) => c.url.includes("/comments")).length, 2);
  });

  it("fails, unreadable, when the last page the cap allows is full", async () => {
    const full = Array.from({ length: 100 }, () => ({
      author_association: "NONE",
      created_at: new Date(NOW).toISOString(),
      body: "spam",
    }));
    const { fetchImpl, calls } = makeFetchMock([
      judgeFromRoute,
      {
        method: "GET",
        path: `/issues/${HEARTBEAT_ISSUE}/comments`,
        body: full,
      },
    ]);
    const verdict = await readHeartbeat({
      token: "t",
      repo: "o/r",
      fetchImpl,
      now: NOW,
    });
    assert.equal(verdict.ok, false);
    assert.equal(verdict.readable, false);
    assert.match(verdict.reason, /more than 1000 comments/);
    assert.equal(calls.filter((c) => c.url.includes("/comments")).length, 10);
  });

  it("fails, unreadable, when the comments or the runs can't be read", async () => {
    const commentsDown = makeFetchMock([
      judgeFromRoute,
      {
        method: "GET",
        path: `/issues/${HEARTBEAT_ISSUE}/comments`,
        status: 500,
        body: {},
      },
    ]);
    const a = await readHeartbeat({
      token: "t",
      repo: "o/r",
      fetchImpl: commentsDown.fetchImpl,
      now: NOW,
    });
    assert.equal(a.ok, false);
    assert.equal(a.readable, false);
    assert.match(a.reason, new RegExp(`#${HEARTBEAT_ISSUE}`));

    const runsDown = makeFetchMock([
      { ...judgeFromRoute, status: 403, body: {} },
    ]);
    const b = await readHeartbeat({
      token: "t",
      repo: "o/r",
      fetchImpl: runsDown.fetchImpl,
      now: NOW,
    });
    assert.equal(b.ok, false);
    assert.equal(b.readable, false);
    assert.equal(
      runsDown.calls.some((c) => c.url.includes("/comments")),
      false,
    );
  });
});

describe("runWatchdog", () => {
  const failing = evaluateHeartbeat({
    records: [],
    now: NOW,
    judgeFrom: LONG_AGO,
  });
  const passing = evaluateHeartbeat({
    records: parseRecords(allDone()),
    now: NOW,
    judgeFrom: LONG_AGO,
  });

  it("creates a P2 incident alert, assigned to the owner, listing every routine", async () => {
    const { fetchImpl, calls } = makeFetchMock([
      { method: "GET", path: "/issues?state=all", body: [] },
      { method: "POST", path: "/issues", body: { number: 42 } },
    ]);
    const out = await runWatchdog({
      verdict: failing,
      token: "t",
      repo: "o/r",
      fetchImpl,
    });
    assert.equal(out.outcome, "fail");
    assert.equal(out.alert.action, "created");
    const created = JSON.parse(calls.find((c) => c.method === "POST").body);
    assert.equal(created.title, ALERT.title);
    assert.deepEqual(created.labels, ALERT.labels);
    assert.ok(created.labels.includes(ALERT_LOOKUP_LABEL));
    assert.ok(created.labels.includes("P2"));
    assert.deepEqual(created.assignees, [ALERT_ASSIGNEE]);
    for (const routine of ROUTINES)
      assert.match(created.body, new RegExp(routine.name));
    assert.match(created.body, new RegExp(`/issues/${HEARTBEAT_ISSUE}\\)`));
    assert.doesNotMatch(
      created.body,
      /\b(fixes|closes|close|fix|fixed|resolve|resolves|resolved)\s+#/i,
    );
  });

  it("comments on an open alert instead of filing a second", async () => {
    const { fetchImpl, calls } = makeFetchMock([
      {
        method: "GET",
        path: "/issues?state=all",
        body: [{ number: 42, title: ALERT.title, state: "open" }],
      },
      { method: "PATCH", path: "/issues/42", body: { number: 42 } },
      { method: "POST", path: "/comments", body: {} },
    ]);
    const out = await runWatchdog({
      verdict: failing,
      token: "t",
      repo: "o/r",
      fetchImpl,
    });
    assert.equal(out.alert.action, "commented");
    assert.equal(
      calls.some((c) => c.method === "POST" && c.url.endsWith("/issues")),
      false,
    );
  });

  it("closes the alert when every routine is done", async () => {
    const { fetchImpl, calls } = makeFetchMock([
      {
        method: "GET",
        path: "/issues?state=all",
        body: [{ number: 42, title: ALERT.title, state: "open" }],
      },
      { method: "POST", path: "/comments", body: {} },
      { method: "PATCH", path: "/issues/42", body: { number: 42 } },
    ]);
    const out = await runWatchdog({
      verdict: passing,
      token: "t",
      repo: "o/r",
      fetchImpl,
    });
    assert.deepEqual(out, { outcome: "pass", resolved: true, lookupOk: true });
    assert.ok(
      calls.some(
        (c) => c.method === "PATCH" && JSON.parse(c.body).state === "closed",
      ),
    );
  });

  it("goes red when every routine is done but the alert won't close", async () => {
    const { fetchImpl } = makeFetchMock([
      {
        method: "GET",
        path: "/issues?state=all",
        body: [{ number: 42, title: ALERT.title, state: "open" }],
      },
      { method: "POST", path: "/comments", body: {} },
      { method: "PATCH", path: "/issues/42", status: 502, body: {} },
    ]);
    const out = await runWatchdog({
      verdict: passing,
      token: "t",
      repo: "o/r",
      fetchImpl,
    });
    assert.deepEqual(out, { outcome: "fail", resolved: false, lookupOk: true });
  });

  it("goes red, closing nothing, when the alert lookup fails", async () => {
    const { fetchImpl, calls } = makeFetchMock([
      { method: "GET", path: "/issues?state=all", status: 500, body: {} },
    ]);
    const out = await runWatchdog({
      verdict: passing,
      token: "t",
      repo: "o/r",
      fetchImpl,
    });
    assert.deepEqual(out, {
      outcome: "fail",
      resolved: false,
      lookupOk: false,
    });
    assert.equal(
      calls.some((c) => c.method === "PATCH"),
      false,
    );
  });

  it("raises an unreadable verdict with its reason", () => {
    const body = buildAlertIssueBody({
      verdict: {
        ok: false,
        readable: false,
        routines: [],
        failing: [],
        reason: "could not read the run records",
      },
      repo: "o/r",
      runUrl: "https://example.test/run/1",
    });
    assert.match(body, /- could not read the run records/);
    assert.match(body, /Run: https:\/\/example\.test\/run\/1$/);
  });
});

describe("wiring", () => {
  const workflow = readFileSync(WORKFLOW, "utf8");

  it("runs daily once the day's last routine fire has had its slack and allowance", () => {
    const [, minute, hour] =
      workflow.match(/cron: "(\d+) (\d+) \* \* \*"/) ?? [];
    assert.ok(minute, "daily cron");
    const slot = Number(hour) * 60 + Number(minute);
    const latest = Math.max(...ROUTINES.map((r) => r.hour * 60 + r.minute));
    // So each run judges the same day's fires, and a miss alerts that evening.
    assert.ok(
      slot >= latest + (DST_SHIFT_MS + RUN_ALLOWANCE_MS) / 60000,
      `${hour}:${minute}`,
    );
    assert.match(workflow, new RegExp(`# ${hour}:${minute} UTC is after`));
  });

  it("names no environment and reads with GITHUB_TOKEN only", () => {
    assert.doesNotMatch(workflow, /^\s*environment:/m);
    assert.doesNotMatch(workflow, /^\s*GITHUB_PAT:/m);
    assert.match(
      workflow,
      /^\s*GITHUB_TOKEN: \$\{\{ secrets\.GITHUB_TOKEN \}\}$/m,
    );
    assert.match(workflow, /node scripts\/ci\/routine-heartbeat\.mjs/);
  });

  it("each routine is a skill, and its skill points at the run record", () => {
    for (const routine of ROUTINES) {
      const skill = join(
        REPO_ROOT,
        ".claude",
        "skills",
        routine.slug,
        "SKILL.md",
      );
      assert.ok(existsSync(skill), `${routine.slug} skill`);
      assert.match(
        readFileSync(skill, "utf8"),
        /routines\.md#run-record-all-routines/,
        `${routine.slug} skill`,
      );
    }
  });

  it("the record format routines copy is the one the parser reads, and each skill names its own slug", () => {
    const doc = readFileSync(ROUTINES_DOC, "utf8");
    const format = doc.match(/^\s*(routine-run: .*)$/m)?.[1];
    assert.equal(
      format,
      "routine-run: v1 routine=<slug> outcome=<done|stopped>",
      "routines.md § Run record",
    );
    for (const slug of ROUTINES.map((r) => r.slug)) {
      for (const outcome of ["done", "stopped"]) {
        const line = format
          .replace("<slug>", slug)
          .replace("<done|stopped>", outcome);
        assert.match(line, RECORD_PATTERN, line);
      }
      assert.ok(doc.includes(`\`${slug}\``), `routines.md lists ${slug}`);
    }
    for (const routine of ROUTINES) {
      const skill = readFileSync(
        join(REPO_ROOT, ".claude", "skills", routine.slug, "SKILL.md"),
        "utf8",
      );
      const named = [...skill.matchAll(/`routine=([a-z-]+)`/g)].map(
        (m) => m[1],
      );
      assert.deepEqual(
        [...new Set(named)],
        [routine.slug],
        `${routine.slug} skill`,
      );
    }
  });

  it("the docs name the heartbeat issue, the alert and the schedule slot", () => {
    assert.match(
      readFileSync(ROUTINES_DOC, "utf8"),
      new RegExp(`issues/${HEARTBEAT_ISSUE}\\b`),
    );
    assert.ok(
      readFileSync(ALERT_ROUTING, "utf8").includes(ALERT.title),
      "ALERT_ROUTING.md row",
    );
    assert.match(
      readFileSync(AGENT_INFRA, "utf8"),
      /\| 19:20 \| `routine-heartbeat\.yml` \|/,
    );
  });
});
