/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get hello world */
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/protected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Authenticated route example */
        get: operations["AppController_getProtected"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chapter-protected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chapter-specific protected route example */
        get: operations["AppController_getChapterProtected"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API Health check */
        get: operations["AppController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/clerk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Handle webhooks from Clerk */
        post: operations["ClerkWebhookController_handleWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initiate chapter onboarding and payment */
        post: operations["OnboardingController_initiate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Handle webhooks from Stripe */
        post: operations["StripeWebhookController_handleWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/financials/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an invoice for a member */
        post: operations["FinancialController_createInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/financials/invoices/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get my invoices */
        get: operations["FinancialController_getMyInvoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/financials/invoices/{id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate payment link for an invoice */
        post: operations["FinancialController_payInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rbac/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all roles for the chapter */
        get: operations["RbacController_getRoles"];
        put?: never;
        /** Create a new custom role */
        post: operations["RbacController_createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rbac/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all available permissions */
        get: operations["RbacController_getPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chapters/{id}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new member invite for a chapter */
        post: operations["InviteController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an invite token to join a chapter */
        post: operations["InviteController_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backwork/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a presigned S3 URL for uploading a file */
        get: operations["BackworkController_getUploadUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backwork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save metadata for a newly uploaded resource */
        post: operations["BackworkController_createResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backwork/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a presigned S3 URL for downloading a resource */
        get: operations["BackworkController_getDownloadUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/points/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user point balance and history */
        get: operations["PointsController_getMyPoints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/points/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get chapter leaderboard */
        get: operations["PointsController_getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/points/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manually adjust points (Admin Only - TODO: RBAC) */
        post: operations["PointsController_adjustPoints"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}/qr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a dynamic QR token for an event */
        get: operations["EventController_getQrToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}/qr-check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check in via QR code */
        post: operations["EventController_qrCheckIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all events for the chapter */
        get: operations["EventController_getEvents"];
        put?: never;
        /** Create a new event */
        post: operations["EventController_createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Self-service check-in to an event */
        post: operations["EventController_checkIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get attendance list for an event */
        get: operations["EventController_getAttendance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a push notification token */
        post: operations["NotificationController_registerToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get notification history for current user */
        get: operations["NotificationController_getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark a notification as read */
        patch: operations["NotificationController_markRead"];
        trace?: never;
    };
    "/chat/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all accessible channels for the chapter */
        get: operations["ChatController_getChannels"];
        put?: never;
        /** Create a new chat channel (Admin Only - TODO: RBAC) */
        post: operations["ChatController_createChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/channels/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get message history for a channel */
        get: operations["ChatController_getMessages"];
        put?: never;
        /** Send a message to a channel via REST */
        post: operations["ChatController_sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study/geofences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available study locations */
        get: operations["StudyController_getGeofences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study/sessions/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a new study session */
        post: operations["StudyController_startSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study/sessions/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send GPS heartbeat to maintain session */
        post: operations["StudyController_heartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study/sessions/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End study session and claim points */
        post: operations["StudyController_stopSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all members in the chapter */
        get: operations["MemberController_getMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign roles to a member */
        patch: operations["MemberController_updateRoles"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ClerkWebhookDto: {
            /** @description The data object of the webhook */
            data: Record<string, never>;
            /** @description The object type */
            object: string;
            /** @description The type of event */
            type: string;
        };
        OnboardingInitDto: {
            /** @description The formal name of the fraternity chapter */
            name: string;
            /** @description The university or institution name */
            university: string;
            /** @description Optional Clerk Organization ID if already created */
            clerkOrganizationId?: string;
        };
        CreateInvoiceDto: {
            /** @example Fall 2026 Dues */
            title: string;
            /** @example Semester membership fees */
            description?: string;
            /**
             * @description Amount in cents ($500.00)
             * @example 50000
             */
            amount: number;
            /** @example user-uuid */
            userId: string;
            /** @example 2026-09-01T00:00:00Z */
            dueDate: string;
        };
        CreateRoleDto: {
            /** @example Social Chair */
            name: string;
            /**
             * @example [
             *       "events:create",
             *       "events:update"
             *     ]
             */
            permissions: string[];
        };
        RoleResponseDto: {
            id: string;
            chapterId: string;
            name: string;
            permissions: string[];
            isSystem: boolean;
            createdAt: string;
        };
        CreateInviteDto: {
            /**
             * @description The role assigned to the new member
             * @example member
             */
            role: string;
        };
        AcceptInviteDto: {
            /** @description The secure token from the invite */
            token: string;
        };
        CreateBackworkResourceDto: {
            /** @example CS101 */
            courseCode: string;
            /** @example Intro to Computer Science */
            courseName: string;
            /** @example Dr. Smith */
            professorName: string;
            /** @example Fall 2024 */
            term: string;
            /** @example Final Exam 2024 */
            title: string;
            s3Key: string;
            fileHash: string;
            tags: string[];
        };
        AdjustPointsDto: {
            /** @example u1-uuid */
            userId: string;
            /** @example 10 */
            amount: number;
            /** @example SERVICE */
            category: string;
            /** @example Helped with kitchen cleaning */
            description: string;
            metadata?: Record<string, never>;
        };
        QrCheckInDto: {
            /** @example jwt-token-string */
            token: string;
        };
        CreateEventDto: {
            /** @example Chapter Meeting */
            name: string;
            /** @example Weekly general assembly */
            description?: string;
            /** @example 2026-02-14T18:00:00Z */
            startTime: string;
            /** @example 2026-02-14T19:00:00Z */
            endTime: string;
            /** @example 10 */
            pointValue: number;
            /** @example true */
            isMandatory: boolean;
        };
        RegisterPushTokenDto: {
            /** @example ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx] */
            token: string;
            /** @example iPhone 15 Pro */
            deviceName?: string;
        };
        CreateChatChannelDto: {
            /** @example General */
            name: string;
            /** @example Main chapter discussion */
            description?: string;
            /**
             * @default PUBLIC
             * @enum {string}
             */
            type: "PUBLIC" | "PRIVATE" | "ROLE_GATED";
            allowedRoleIds?: string[];
        };
        SendChatMessageDto: {
            /** @example Hello everyone! */
            content: string;
            metadata?: Record<string, never>;
        };
        StartSessionDto: {
            /** @example geofence-uuid */
            geofenceId: string;
            /** @example 37.7749 */
            latitude: number;
            /** @example -122.4194 */
            longitude: number;
        };
        HeartbeatDto: {
            /** @example 37.7749 */
            latitude: number;
            /** @example -122.4194 */
            longitude: number;
        };
        MemberResponseDto: {
            id: string;
            userId: string;
            chapterId: string;
            roleIds: string[];
            createdAt: string;
            updatedAt: string;
        };
        UpdateMemberRolesDto: {
            /**
             * @example [
             *       "role-uuid-1",
             *       "role-uuid-2"
             *     ]
             */
            roleIds: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_getProtected: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_getChapterProtected: {
        parameters: {
            query?: never;
            header?: {
                /** @description Chapter UUID */
                "x-chapter-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_getHealth: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClerkWebhookController_handleWebhook: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClerkWebhookDto"];
            };
        };
        responses: {
            /** @description Webhook received */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid signature */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OnboardingController_initiate: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingInitDto"];
            };
        };
        responses: {
            /** @description Onboarding initiated, returns checkout URL */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StripeWebhookController_handleWebhook: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid signature */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FinancialController_createInvoice: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvoiceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FinancialController_getMyInvoices: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FinancialController_payInvoice: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RbacController_getRoles: {
        parameters: {
            query?: never;
            header: {
                "x-chapter-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponseDto"][];
                };
            };
        };
    };
    RbacController_createRole: {
        parameters: {
            query?: never;
            header: {
                "x-chapter-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponseDto"];
                };
            };
        };
    };
    RbacController_getPermissions: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    InviteController_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description Chapter UUID */
                "x-chapter-id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteDto"];
            };
        };
        responses: {
            /** @description Invite created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InviteController_accept: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInviteDto"];
            };
        };
        responses: {
            /** @description Invite accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BackworkController_getUploadUrl: {
        parameters: {
            query: {
                filename: string;
                contentType: string;
            };
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BackworkController_createResource: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBackworkResourceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BackworkController_getDownloadUrl: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PointsController_getMyPoints: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PointsController_getLeaderboard: {
        parameters: {
            query: {
                limit: number;
            };
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PointsController_adjustPoints: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdjustPointsDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_getQrToken: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_qrCheckIn: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QrCheckInDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_getEvents: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_createEvent: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_checkIn: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_getAttendance: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationController_registerToken: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPushTokenDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationController_getHistory: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationController_markRead: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatController_getChannels: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatController_createChannel: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChatChannelDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatController_getMessages: {
        parameters: {
            query: {
                limit: number;
                offset: number;
            };
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatController_sendMessage: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendChatMessageDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudyController_getGeofences: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudyController_startSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSessionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudyController_heartbeat: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudyController_stopSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Chapter ID for multi-tenancy */
                "x-chapter-id"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MemberController_getMembers: {
        parameters: {
            query?: never;
            header: {
                "x-chapter-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponseDto"][];
                };
            };
        };
    };
    MemberController_updateRoles: {
        parameters: {
            query?: never;
            header: {
                "x-chapter-id": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberRolesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponseDto"];
                };
            };
        };
    };
}
