#!/usr/bin/env bash
# Loads reference/seed data into the LOCAL Supabase stack after migrations have applied.
# Sourced, not executed. No `set -e` here — callers decide their own error policy.
#
# Sourced by BOTH bootstrap paths, for the same reason local-postgres-acl.sh is:
#   * scripts/cloud-sandbox-up.sh  — Claude Code web sandbox (primary dev env)
#   * scripts/local-dev-setup.sh   — laptop / WSL (secondary dev env)
#
# REQUIRES scripts/lib/local-postgres-acl.sh to have been sourced first — this file uses
# `frapp_run_local_sql` for the "how do I reach the local database" dispatch (host psql
# against the CLI-reported URL, falling back to `docker exec`, with a loopback guard).
# That logic is deliberately not duplicated here; it took four review rounds to get right
# in PR #801 and there should only ever be one copy of it.
#
# Portability: same constraints as local-postgres-acl.sh — no bash arrays, no
# `"${arr[@]}"` expansion, so this stays safe on a stock macOS bash 3.2 under `set -u`.

# Log prefix, looked up at CALL time so callers may set it before or after sourcing.
: "${FRAPP_SEED_LOG_PREFIX:=[local-seed-data]}"

frapp_seed_log() {
  printf '%s %s\n' "${FRAPP_SEED_LOG_PREFIX}" "$*" >&2
}

# Load supabase/seed/chapter_directory.csv into public.chapter_directory.
#
#   frapp_load_chapter_directory <project_root> [supabase_cli_command...]
#
# Returns 0 on success, non-zero on failure. Callers treat failure as a WARNING rather
# than fatal, and the asymmetry with the ACL repair is deliberate: without the ACL repair
# the API cannot read any table at all, whereas without the directory only onboarding
# autofill degrades — and it degrades to a path that already exists and works
# (chapter_onboarding.service.ts records a chapter_directory_requests row on a miss).
# Aborting a whole bootstrap over reference data would be the wrong trade.
#
# Set FRAPP_SKIP_DIRECTORY_LOAD=1 to skip it deliberately, mirroring FRAPP_SKIP_ACL_REPAIR.
#
# The SQL is generated by a Node script rather than written here because the CSV is the
# source of truth and issue #232 grows it to ~2,000 rows. See
# scripts/load-chapter-directory.mjs for why the generated SQL is an UPDATE-then-INSERT
# rather than the more obvious ON CONFLICT (short version: there is no unique constraint
# to conflict on, and a delete/re-insert would null out chapters.directory_id).
frapp_load_chapter_directory() {
  local project_root="$1"
  shift
  local sql rc

  if [ -n "${FRAPP_SKIP_DIRECTORY_LOAD:-}" ]; then
    frapp_seed_log "Skipping the chapter directory load (FRAPP_SKIP_DIRECTORY_LOAD set)."
    return 0
  fi

  if ! command -v node >/dev/null 2>&1; then
    frapp_seed_log "WARN: node not found; skipping the chapter directory load."
    return 1
  fi

  # Generate first, load second. The generator refuses to emit SQL for a seed that fails
  # validation, so a malformed color can never reach the database — where it would become
  # invisible, since derivePalette silently substitutes bronze for an unparseable hex.
  #
  # `cd` is silenced rather than merely error-suppressed: with CDPATH set it echoes the
  # resolved directory to stdout, which the command substitution would splice onto the
  # front of the generated SQL. Same guard as local-postgres-acl.sh's db_url capture.
  sql=$(cd "${project_root}" >/dev/null 2>&1 && node scripts/load-chapter-directory.mjs) && rc=0 || rc=$?
  if [ "${rc}" -ne 0 ] || [ -z "${sql}" ]; then
    frapp_seed_log "WARN: could not generate the chapter directory load SQL."
    frapp_seed_log "      Run 'npm run check:chapter-directory-seed' to see why."
    return 1
  fi

  frapp_run_local_sql "${project_root}" "${sql}" "chapter directory load" "$@"
}
