// Connection + availability plumbing for the live-PostgREST integration suite.
//
// Everything here is about one question: *is there a real Supabase stack to
// talk to?* The suite's contract is that it proves things against real
// PostgREST when a stack exists and disappears quietly when one doesn't — it
// must never fail merely because Docker isn't running. `global-setup.ts`
// answers the question once; the specs read the answer through
// `describeIntegration`.

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { createClient } from '@supabase/supabase-js';
import type {
  Database,
  FrappSupabaseClient,
} from '../../src/infrastructure/supabase/database.types';

/**
 * Set by {@link probeStack} in `globalSetup`, read by {@link describeIntegration}
 * in each worker. Jest forks its workers *after* `globalSetup` returns and
 * copies `process.env` into them, so a plain env var is the supported way to
 * hand a decision from the one to the other.
 */
export const STACK_ENV_FLAG = 'FRAPP_INTEGRATION_STACK';

/**
 * Parse `KEY=value` / `KEY="value"` pairs out of an env file.
 *
 * Hand-rolled rather than pulling in `dotenv`, which is not a dependency of
 * this workspace: `apps/api/.env.local` is generated by
 * `scripts/cloud-sandbox-up.sh` in exactly this shape, and a test harness is a
 * poor reason to add a runtime dependency. Unparseable lines are skipped
 * rather than throwing — a malformed comment should not take down the suite.
 */
function parseEnvFile(contents: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const rawLine of contents.split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

/**
 * Load `apps/api/.env.local` into `process.env` without clobbering anything
 * already set.
 *
 * Existing values win so CI (or a developer pointing at a different stack) can
 * override by exporting, matching how `ConfigModule.forRoot({ envFilePath })`
 * behaves for the app itself in `src/app.module.ts`.
 */
export function loadLocalEnv(): void {
  try {
    const contents = readFileSync(
      join(__dirname, '..', '..', '.env.local'),
      'utf8',
    );
    for (const [key, value] of Object.entries(parseEnvFile(contents))) {
      if (process.env[key] === undefined) process.env[key] = value;
    }
  } catch {
    // No `.env.local` is a normal state — a CI run with the stack's connection
    // details exported, or no stack at all. `probeStack` decides either way.
  }
}

export interface StackCredentials {
  url: string;
  serviceRoleKey: string;
}

export function readCredentials(): StackCredentials | null {
  const url = process.env.SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !serviceRoleKey) return null;
  return { url, serviceRoleKey };
}

/**
 * Decide whether a usable stack is reachable, and say so on stderr.
 *
 * "Usable" is deliberately stricter than "listening": the probe issues a real
 * PostgREST read with the service-role key. A stack that answers but denies
 * DML — the exact state #703/#725 describe, where `service_role` was left
 * without table grants — would let every test fail with a confusing error
 * instead of skipping. Requiring a 2xx here turns that into a clean skip.
 */
export async function probeStack(): Promise<boolean> {
  const creds = readCredentials();
  if (!creds) return false;

  try {
    const response = await fetch(
      `${creds.url}/rest/v1/chapters?select=id&limit=1`,
      {
        headers: {
          apikey: creds.serviceRoleKey,
          Authorization: `Bearer ${creds.serviceRoleKey}`,
        },
        signal: AbortSignal.timeout(5_000),
      },
    );
    return response.ok;
  } catch {
    return false;
  }
}

/**
 * A service-role client, which bypasses RLS.
 *
 * That is correct for this suite and worth being explicit about: these tests
 * exist to prove the *PostgREST request shapes* the report service builds are
 * accepted and correctly scoped. `ReportService` itself runs under the
 * service-role client in production (`SUPABASE_CLIENT`), so chapter isolation
 * there is a property of the queries, not of RLS — which is precisely why it
 * needs testing. RLS policy coverage is a separate concern, and lives in the
 * PGlite harness (`scripts/check-pglite-migrations.mjs`), whose black-box tier
 * reads each table as a non-owner role.
 */
export function createServiceRoleClient(): FrappSupabaseClient {
  const creds = readCredentials();
  if (!creds) {
    throw new Error(
      'SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY are unset — createServiceRoleClient() ' +
        'was called in a run that should have been skipped.',
    );
  }
  return createClient<Database>(creds.url, creds.serviceRoleKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

export function isStackAvailable(): boolean {
  return process.env[STACK_ENV_FLAG] === 'up';
}

/**
 * `describe` when a stack is reachable, `describe.skip` when it is not.
 *
 * The acceptance criterion is that an absent stack skips *cleanly* rather than
 * failing, so the decision is a synchronous read of the flag `globalSetup`
 * already set — no async work, no `beforeAll` that can throw.
 *
 * A function rather than a `const` holding `describe`/`describe.skip`, because
 * this module is also imported by `global-setup.ts`, which Jest runs in the
 * parent process **before** any test environment exists. Resolving `describe`
 * at module load crashed the run there with `describe is not defined`; touching
 * it only when a spec calls this keeps the module safe to import from both.
 */
export function describeIntegration(name: string, fn: () => void): void {
  if (isStackAvailable()) {
    describe(name, fn);
  } else {
    describe.skip(name, fn);
  }
}
