#!/usr/bin/env bash
# Cloud sandbox PER-SESSION bringup. Idempotent. Brings the local stack up and writes
# apps/api/.env.local so the API boots without Infisical:
#
#   1. start the Docker daemon (does not persist across sessions)
#   2. supabase start (fast — images were cached by cloud-sandbox-setup.sh)
#   3. supabase db push --local
#   4. write apps/api/.env.local from `supabase status` + Stripe env vars
#
# Auto-launched in the background by .claude/hooks/session-start.sh (gated on the
# /etc/frapp-cloud-sandbox marker or FRAPP_CLOUD_SANDBOX=1), or run directly. Writes a
# .cloud-sandbox-up.done / .cloud-sandbox-up.failed sentinel at repo root so callers can
# poll completion. See docs/internal/environment/CLOUD_SANDBOX.md.
set -uo pipefail

ROOT="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$ROOT"
# shellcheck source=scripts/lib/cloud-sandbox-common.sh
. "$ROOT/scripts/lib/cloud-sandbox-common.sh"

DONE_SENTINEL="$ROOT/.cloud-sandbox-up.done"
FAILED_SENTINEL="$ROOT/.cloud-sandbox-up.failed"
rm -f "$DONE_SENTINEL" "$FAILED_SENTINEL"

fail() {
  cs_log "ERROR: $1"
  printf '%s — %s\n' "$(date -u +%FT%TZ)" "$1" >"$FAILED_SENTINEL"
  exit 1
}

# Write apps/api/.env.local from the live local Supabase + Stripe env vars. Real Stripe
# test keys are used when present; otherwise clearly-marked placeholders that satisfy
# the non-empty check in apps/api/src/config/env.validation.ts (the API boots; billing
# endpoints that call Stripe will not work). The file is gitignored.
write_env_local() {
  local envfile="$ROOT/apps/api/.env.local"
  local supa

  # Preferred: map Supabase's status output straight onto the API's variable names.
  supa=$(cs_supabase status -o env \
    --override-name api.url=SUPABASE_URL \
    --override-name auth.anon_key=SUPABASE_ANON_KEY \
    --override-name auth.service_role_key=SUPABASE_SERVICE_ROLE_KEY 2>/dev/null)

  # Fallback for CLI versions that don't support --override-name: remap default names.
  if ! printf '%s' "$supa" | grep -q '^SUPABASE_URL='; then
    supa=$(cs_supabase status -o env 2>/dev/null) || return 1
    supa=$(printf '%s\n' "$supa" \
      | sed -e 's/^API_URL=/SUPABASE_URL=/' \
            -e 's/^ANON_KEY=/SUPABASE_ANON_KEY=/' \
            -e 's/^SERVICE_ROLE_KEY=/SUPABASE_SERVICE_ROLE_KEY=/' \
      | grep -E '^SUPABASE_(URL|ANON_KEY|SERVICE_ROLE_KEY)=')
  fi

  printf '%s' "$supa" | grep -q '^SUPABASE_URL=' || return 1

  {
    echo "# Generated by scripts/cloud-sandbox-up.sh — DO NOT COMMIT (gitignored)."
    echo "# Local Supabase values are regenerated each session from 'supabase status'."
    printf '%s\n' "$supa"
    echo "STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-sk_test_placeholder_cloud_sandbox}"
    echo "STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-whsec_placeholder_cloud_sandbox}"
    echo "STRIPE_PRICE_ID=${STRIPE_PRICE_ID:-price_placeholder_cloud_sandbox}"
    echo "PORT=3001"
    echo "NODE_ENV=development"
  } >"$envfile"

  if [ -z "${STRIPE_SECRET_KEY:-}" ]; then
    cs_log "NOTE: no STRIPE_SECRET_KEY in env — wrote Stripe placeholders. Billing endpoints will not work."
  fi
}

cs_ensure_docker_daemon || fail "Docker daemon did not start."
cs_docker_login_if_creds

cs_log "Starting Supabase (images cached)..."
# Exclude the Deno edge-runtime container: it sets an rlimit (RLIMIT_NOFILE) the
# cloud sandbox denies ("error setting rlimit type 7: operation not permitted"),
# which otherwise aborts the whole `supabase start`. The API connects to Postgres
# directly and hot-path logic has moved into NestJS (ADR-11/ADR-12), so edge
# functions are not needed for local dev here. Override with FRAPP_SUPABASE_START_ARGS
# if a session genuinely needs them.
SUPABASE_START_ARGS="${FRAPP_SUPABASE_START_ARGS:--x edge-runtime}"
# shellcheck disable=SC2086
cs_supabase start $SUPABASE_START_ARGS || fail "'supabase start' failed."

cs_log "Applying local migrations..."
cs_supabase db push --local || fail "'supabase db push --local' failed."

cs_log "Writing apps/api/.env.local..."
write_env_local || fail "Could not write apps/api/.env.local from 'supabase status'."

printf '%s\n' "$(date -u +%FT%TZ)" >"$DONE_SENTINEL"
cs_log "Cloud sandbox ready. Boot the API with: npm run start:dev -w apps/api"
