#!/usr/bin/env bash
# Cloud sandbox PER-SESSION bringup. Idempotent. Brings the local stack up and writes
# apps/api/.env.local so the API boots without Infisical:
#
#   1. start the Docker daemon (does not persist across sessions)
#   2. supabase start (fast — images were cached by cloud-sandbox-setup.sh)
#   3. supabase db push --local
#   4. write apps/api/.env.local from `supabase status` + Stripe env vars
#
# Auto-launched in the background by .claude/hooks/session-start.sh (gated on the
# /etc/frapp-cloud-sandbox marker or FRAPP_CLOUD_SANDBOX=1), or run directly. Writes a
# .cloud-sandbox-up.done / .cloud-sandbox-up.failed sentinel at repo root so callers can
# poll completion. See docs/internal/environment/CLOUD_SANDBOX.md.
set -uo pipefail

ROOT="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$ROOT"
# shellcheck source=scripts/lib/cloud-sandbox-common.sh
. "$ROOT/scripts/lib/cloud-sandbox-common.sh"

DONE_SENTINEL="$ROOT/.cloud-sandbox-up.done"
FAILED_SENTINEL="$ROOT/.cloud-sandbox-up.failed"
rm -f "$DONE_SENTINEL" "$FAILED_SENTINEL"

fail() {
  cs_log "ERROR: $1"
  printf '%s — %s\n' "$(date -u +%FT%TZ)" "$1" >"$FAILED_SENTINEL"
  exit 1
}

# Write apps/api/.env.local from the live local Supabase + Stripe env vars. Real Stripe
# test keys are used when present; otherwise clearly-marked placeholders that satisfy
# the non-empty check in apps/api/src/config/env.validation.ts (the API boots; billing
# endpoints that call Stripe will not work). The file is gitignored.
write_env_local() {
  local envfile="$ROOT/apps/api/.env.local"
  local supa

  # Preferred: map Supabase's status output straight onto the API's variable names.
  supa=$(cs_supabase status -o env \
    --override-name api.url=SUPABASE_URL \
    --override-name auth.anon_key=SUPABASE_ANON_KEY \
    --override-name auth.service_role_key=SUPABASE_SERVICE_ROLE_KEY 2>/dev/null)

  # Fallback for CLI versions that don't support --override-name: remap default names.
  if ! printf '%s' "$supa" | grep -q '^SUPABASE_URL='; then
    supa=$(cs_supabase status -o env 2>/dev/null) || return 1
    supa=$(printf '%s\n' "$supa" \
      | sed -e 's/^API_URL=/SUPABASE_URL=/' \
            -e 's/^ANON_KEY=/SUPABASE_ANON_KEY=/' \
            -e 's/^SERVICE_ROLE_KEY=/SUPABASE_SERVICE_ROLE_KEY=/' \
      | grep -E '^SUPABASE_(URL|ANON_KEY|SERVICE_ROLE_KEY)=')
  fi

  # Validate every variable apps/api/src/config/env.validation.ts hard-requires, not just
  # the URL. `supabase status` omits the auth keys when gotrue is stopped or excluded (e.g.
  # a FRAPP_SUPABASE_START_ARGS override adding `-x gotrue`), and checking only SUPABASE_URL
  # let that write a .env.local the API cannot boot from — while still returning 0 and
  # landing the .cloud-sandbox-up.done success sentinel.
  local key missing=""
  for key in SUPABASE_URL SUPABASE_ANON_KEY SUPABASE_SERVICE_ROLE_KEY; do
    printf '%s' "$supa" | grep -q "^${key}=" || missing="${missing} ${key}"
  done
  if [ -n "$missing" ]; then
    cs_log "ERROR: 'supabase status' output is missing:${missing} — is the auth (gotrue) container running?"
    return 1
  fi

  {
    echo "# Generated by scripts/cloud-sandbox-up.sh — DO NOT COMMIT (gitignored)."
    echo "# Local Supabase values are regenerated each session from 'supabase status'."
    printf '%s\n' "$supa"
    echo "STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-sk_test_placeholder_cloud_sandbox}"
    echo "STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-whsec_placeholder_cloud_sandbox}"
    echo "STRIPE_PRICE_ID=${STRIPE_PRICE_ID:-price_placeholder_cloud_sandbox}"
    echo "PORT=3001"
    echo "NODE_ENV=development"
  } >"$envfile"

  if [ -z "${STRIPE_SECRET_KEY:-}" ]; then
    cs_log "NOTE: no STRIPE_SECRET_KEY in env — wrote Stripe placeholders. Billing endpoints will not work."
  fi
}

cs_ensure_docker_daemon || fail "Docker daemon did not start."
cs_docker_login_if_creds

cs_log "Starting Supabase (images cached)..."
# Start args (incl. the mandatory edge-runtime exclusion) live in the shared lib as
# CS_SUPABASE_START_ARGS so bringup and the setup pre-pull cannot drift apart.
# shellcheck disable=SC2086
cs_supabase start $CS_SUPABASE_START_ARGS || fail "'supabase start' failed."

cs_log "Applying local migrations..."
cs_supabase db push --local || fail "'supabase db push --local' failed."

cs_log "Writing apps/api/.env.local..."
write_env_local || fail "Could not write apps/api/.env.local from 'supabase status'."

printf '%s\n' "$(date -u +%FT%TZ)" >"$DONE_SENTINEL"
cs_log "Cloud sandbox ready. Boot the API with: npm run start:dev -w apps/api"
