-- The chapter directory's reference rows, for every environment (#840, item 18
-- of the 2026-09-06 launch session).
--
-- `chapter_directory` is the global table the onboarding wizard searches to
-- autofill a new chapter's identity. Its rows come from
-- supabase/seed/chapter_directory.csv, and until this migration only the local
-- bootstrap scripts ever loaded them: both hosted projects had an EMPTY table,
-- so every search in the production wizard would have answered "We couldn't
-- find … in our directory" and pushed the first officer to the manual form.
-- Migrations are the one path that reaches staging and production, so the load
-- rides one.
--
-- The body below is the output of `npm run load:chapter-directory`
-- (scripts/load-chapter-directory.mjs) with its own `begin`/`commit` removed —
-- `supabase db push` already wraps each migration in a transaction (the temp
-- table is dropped explicitly at the end instead). Everything
-- load-bearing about the loader holds here too (docs/guides/database.md
-- § Reference data): it is idempotent, it preserves existing row ids (so
-- `chapters.directory_id` never detaches), it updates only rows whose `source`
-- is 'seed', and it inserts only what is missing by the natural key
-- (org_letters, university, chapter_designation). Re-running it — locally,
-- where the bootstrap has already loaded the same CSV — changes nothing.
--
-- To ship a changed CSV later: regenerate with the same command into a NEW
-- migration file. Never edit this one.

-- Generated by scripts/load-chapter-directory.mjs — do not edit by hand.
-- Source: supabase/seed/chapter_directory.csv (50 rows)
-- Idempotent: safe to re-run. See the script for why this is not ON CONFLICT.


create temporary table _seed_chapter_directory (
  org_letters          text not null,
  org_name             text not null,
  archetype            text not null,
  chapter_designation  text,
  university           text not null,
  university_short     text not null,
  founded_year         int,
  default_colors       jsonb not null,
  website              text,
  source               text not null
);

insert into _seed_chapter_directory (
  org_letters, org_name, archetype, chapter_designation, university,
  university_short, founded_year, default_colors, website, source
) values
  ('ΣΦΕ', 'Sigma Phi Epsilon', 'ifc', 'California Eta', 'UCLA', 'UCLA', 1948, '{"accent":"#C9A56F"}'::jsonb, 'https://sigmaphiepsilon.org', 'seed'),
  ('ΠΚΑ', 'Pi Kappa Alpha', 'ifc', 'Alpha Chi', 'University of Tennessee', 'UTK', 1947, '{"accent":"#BF0A30"}'::jsonb, 'https://pka.com', 'seed'),
  ('ΣΑΕ', 'Sigma Alpha Epsilon', 'ifc', 'Tennessee Alpha', 'Vanderbilt University', 'Vandy', 1943, '{"accent":"#C9A56F"}'::jsonb, 'https://sae.net', 'seed'),
  ('ΦΔΘ', 'Phi Delta Theta', 'ifc', 'Tennessee Beta', 'University of Michigan', 'UMich', 1887, '{"accent":"#C9A56F"}'::jsonb, 'https://phideltatheta.org', 'seed'),
  ('ΚΑ', 'Kappa Alpha Order', 'ifc', 'Alpha', 'Washington and Lee', 'WLU', 1865, '{"accent":"#C9A56F"}'::jsonb, 'https://kappaalphaorder.org', 'seed'),
  ('ΑΤΩ', 'Alpha Tau Omega', 'ifc', 'Alpha Sigma', 'Purdue University', 'Purdue', 1922, '{"accent":"#C9A56F"}'::jsonb, 'https://ato.org', 'seed'),
  ('ΦΚΨ', 'Phi Kappa Psi', 'ifc', 'Indiana Gamma', 'Indiana University', 'IU', 1901, '{"accent":"#C9A56F"}'::jsonb, 'https://phikappapsi.com', 'seed'),
  ('ΒΘΠ', 'Beta Theta Pi', 'ifc', 'Beta Iota', 'Ohio State', 'OSU', 1899, '{"accent":"#C9A56F"}'::jsonb, 'https://betatheta.pi.org', 'seed'),
  ('ΔΤΔ', 'Delta Tau Delta', 'ifc', 'Gamma Eta', 'University of Georgia', 'UGA', 1920, '{"accent":"#C9A56F"}'::jsonb, 'https://delts.org', 'seed'),
  ('ΛΧΑ', 'Lambda Chi Alpha', 'ifc', 'Zeta Omega', 'Michigan State', 'MSU', 1915, '{"accent":"#C9A56F"}'::jsonb, 'https://lambdachi.org', 'seed'),
  ('ΑΕΠ', 'Alpha Epsilon Pi', 'ifc', 'Epsilon Pi', 'University of Florida', 'UF', 1960, '{"accent":"#C9A56F"}'::jsonb, 'https://aepi.org', 'seed'),
  ('ΑΧΡ', 'Alpha Chi Rho', 'ifc', 'Phi Chi', 'Rutgers University', 'Rutgers', 1895, '{"accent":"#C9A56F"}'::jsonb, 'https://alphachirho.org', 'seed'),
  ('ΣΝ', 'Sigma Nu', 'ifc', 'Gamma Theta', 'LSU', 'LSU', 1892, '{"accent":"#C9A56F"}'::jsonb, 'https://sigmanu.org', 'seed'),
  ('ΦΓΔ', 'Phi Gamma Delta', 'ifc', 'Pi Tau', 'RPI', 'RPI', 1878, '{"accent":"#C9A56F"}'::jsonb, 'https://phigam.org', 'seed'),
  ('ΘΧ', 'Theta Chi', 'ifc', 'Alpha Rho', 'Northeastern', 'NEU', 1910, '{"accent":"#C9A56F"}'::jsonb, 'https://thetachi.org', 'seed'),
  ('ΑΦΑ', 'Alpha Phi Alpha', 'nphc', 'Beta Chapter', 'Howard University', 'Howard', 1906, '{"accent":"#C9A56F"}'::jsonb, 'https://alpha-phi-alpha.org', 'seed'),
  ('ΩΨΦ', 'Omega Psi Phi', 'nphc', 'Chi Chapter', 'North Carolina A&T', 'NCAT', 1911, '{"accent":"#C9A56F"}'::jsonb, 'https://oppf.org', 'seed'),
  ('ΚΑΨ', 'Kappa Alpha Psi', 'nphc', 'Gamma Chapter', 'Indiana University', 'IU', 1911, '{"accent":"#C9A56F"}'::jsonb, 'https://kappaalphapsi1911.com', 'seed'),
  ('ΦΒΣ', 'Phi Beta Sigma', 'nphc', 'Alpha Chapter', 'Howard University', 'Howard', 1914, '{"accent":"#C9A56F"}'::jsonb, 'https://pbs1914.org', 'seed'),
  ('ΙΦΘ', 'Iota Phi Theta', 'nphc', 'Alpha Iota', 'Morgan State', 'Morgan', 1963, '{"accent":"#C9A56F"}'::jsonb, 'https://iotaphitheta.org', 'seed'),
  ('ΑΚΑ', 'Alpha Kappa Alpha', 'npc', 'Beta Chapter', 'Howard University', 'Howard', 1908, '{"accent":"#FF69B4"}'::jsonb, 'https://aka1908.com', 'seed'),
  ('ΔΣΘ', 'Delta Sigma Theta', 'npc', 'Alpha Chapter', 'Howard University', 'Howard', 1913, '{"accent":"#C9A56F"}'::jsonb, 'https://dst1913.org', 'seed'),
  ('ΖΦΒ', 'Zeta Phi Beta', 'npc', 'Alpha Chapter', 'Howard University', 'Howard', 1920, '{"accent":"#FFFFFF"}'::jsonb, 'https://zphib1920.org', 'seed'),
  ('ΣΓΡ', 'Sigma Gamma Rho', 'npc', 'Alpha Chapter', 'Butler University', 'Butler', 1922, '{"accent":"#C9A56F"}'::jsonb, 'https://sgrho1922.org', 'seed'),
  ('ΔΔΔ', 'Delta Delta Delta', 'npc', 'Alpha Alpha', 'Boston University', 'BU', 1888, '{"accent":"#C0C0C0"}'::jsonb, 'https://tridelta.org', 'seed'),
  ('ΑΦ', 'Alpha Phi', 'npc', 'Alpha Alpha', 'Syracuse University', 'SU', 1872, '{"accent":"#C9A56F"}'::jsonb, 'https://alphaphi.org', 'seed'),
  ('ΧΩ', 'Chi Omega', 'npc', 'Alpha Lambda', 'University of Texas', 'UT', 1905, '{"accent":"#C9A56F"}'::jsonb, 'https://chiomega.com', 'seed'),
  ('ΠΒΦ', 'Pi Beta Phi', 'npc', 'Illinois Beta', 'Northwestern University', 'NW', 1891, '{"accent":"#C9A56F"}'::jsonb, 'https://pibetaphi.org', 'seed'),
  ('ΑΔΠ', 'Alpha Delta Pi', 'npc', 'Theta', 'Emory University', 'Emory', 1897, '{"accent":"#FFFFFF"}'::jsonb, 'https://alphadeltapi.org', 'seed'),
  ('ΓΦΒ', 'Gamma Phi Beta', 'npc', 'Alpha Gamma', 'Michigan', 'UMich', 1874, '{"accent":"#C9A56F"}'::jsonb, 'https://gammaphibeta.org', 'seed'),
  ('ΛΘΑ', 'Lambda Theta Alpha', 'mgc', 'Alpha Chapter', 'Kean University', 'Kean', 1975, '{"accent":"#C9A56F"}'::jsonb, 'https://lambdathetaalpha.org', 'seed'),
  ('ΛΥΛ', 'Lambda Upsilon Lambda', 'mgc', 'Beta Chapter', 'Cornell University', 'Cornell', 1982, '{"accent":"#C9A56F"}'::jsonb, 'https://launidad.org', 'seed'),
  ('ΘΔΧ', 'Theta Delta Chi', 'mgc', 'Alpha Xi', 'UCLA', 'UCLA', 1992, '{"accent":"#C9A56F"}'::jsonb, 'https://thetadeltachi.org', 'seed'),
  ('ΑΚΔΦ', 'Alpha Kappa Delta Phi', 'mgc', 'Epsilon Chapter', 'UC Berkeley', 'UCB', 1990, '{"accent":"#C9A56F"}'::jsonb, 'https://akdphi.org', 'seed'),
  ('ΑΣΑ', 'Alpha Sigma Alpha', 'npc', 'Alpha Chi', 'Indiana State University', 'ISU', 1901, '{"accent":"#C9A56F"}'::jsonb, 'https://alphasigmaalpha.org', 'seed'),
  ('ΦΜ', 'Phi Mu', 'npc', 'Alpha Alpha', 'Wesleyan', 'Wesleyan', 1852, '{"accent":"#C9A56F"}'::jsonb, 'https://phimu.org', 'seed'),
  ('ΑΞΔ', 'Alpha Xi Delta', 'npc', 'Alpha Nu', 'Northwestern', 'NW', 1893, '{"accent":"#C9A56F"}'::jsonb, 'https://alphaxidelta.org', 'seed'),
  ('ΔΖ', 'Delta Zeta', 'npc', 'Alpha Pi', 'Miami University', 'MU', 1902, '{"accent":"#C9A56F"}'::jsonb, 'https://deltazeta.org', 'seed'),
  ('ΣΔΤ', 'Sigma Delta Tau', 'npc', 'Alpha Theta', 'Cornell University', 'Cornell', 1917, '{"accent":"#C9A56F"}'::jsonb, 'https://sigmadeltatau.org', 'seed'),
  ('ΤΒΠ', 'Tau Beta Pi', 'honor', 'Alpha Chapter', 'Lehigh University', 'Lehigh', 1885, '{"accent":"#C9A56F"}'::jsonb, 'https://tbp.org', 'seed'),
  ('ΦΒΚ', 'Phi Beta Kappa', 'honor', 'Alpha Chapter', 'William & Mary', 'W&M', 1776, '{"accent":"#C9A56F"}'::jsonb, 'https://pbk.org', 'seed'),
  ('ΠΤΣ', 'Pi Tau Sigma', 'honor', 'Alpha Chapter', 'University of Illinois', 'UIUC', 1915, '{"accent":"#C9A56F"}'::jsonb, 'https://pitausigma.net', 'seed'),
  ('ΘΤ', 'Theta Tau', 'professional', 'Alpha Chapter', 'University of Minnesota', 'UMN', 1904, '{"accent":"#C9A56F"}'::jsonb, 'https://thetatau.org', 'seed'),
  ('ΑΩ', 'Alpha Omega', 'professional', 'Alpha Chapter', 'New York University', 'NYU', 1907, '{"accent":"#C9A56F"}'::jsonb, 'https://alphaomega.com', 'seed'),
  ('ΔΣΠ', 'Delta Sigma Pi', 'professional', 'Alpha Chapter', 'NYU Stern', 'NYU', 1907, '{"accent":"#C9A56F"}'::jsonb, 'https://deltasigmapi.org', 'seed'),
  ('ΑΞΣ', 'Alpha Chi Sigma', 'professional', 'Alpha Chapter', 'University of Wisconsin', 'UW', 1902, '{"accent":"#C9A56F"}'::jsonb, 'https://alphachisigma.org', 'seed'),
  ('ΑΟΠ', 'Alpha Omicron Pi', 'npc', 'Alpha Phi', 'Northwestern', 'NW', 1897, '{"accent":"#C9A56F"}'::jsonb, 'https://alphaomicronpi.org', 'seed'),
  ('ΚΔ', 'Kappa Delta', 'npc', 'Alpha Alpha', 'Longwood University', 'Longwood', 1897, '{"accent":"#C9A56F"}'::jsonb, 'https://kappadelta.org', 'seed'),
  ('ΣΚ', 'Sigma Kappa', 'npc', 'Alpha Delta', 'Colby College', 'Colby', 1874, '{"accent":"#C9A56F"}'::jsonb, 'https://sigmakappa.org', 'seed'),
  ('ΑΓΔ', 'Alpha Gamma Delta', 'npc', 'Alpha Lambda', 'University of Minnesota', 'UMN', 1904, '{"accent":"#C9A56F"}'::jsonb, 'https://alphagammadelta.org', 'seed');

-- The natural key is (org_letters, university, chapter_designation). The
-- designation is nullable, and SQL's NULL <> NULL would make two undesignated
-- rows for the same org+campus look distinct, so it is coalesced on both sides.
--
-- Updates are scoped to rows this loader owns (source = 'seed'). A row curated
-- by hand or arriving from another source keeps its values; the seed never
-- silently overwrites someone's correction.
update chapter_directory d
set
  org_name            = s.org_name,
  archetype           = s.archetype,
  university_short    = s.university_short,
  founded_year        = s.founded_year,
  default_colors      = s.default_colors,
  website             = s.website
from _seed_chapter_directory s
where d.org_letters = s.org_letters
  and d.university  = s.university
  and coalesce(d.chapter_designation, '') = coalesce(s.chapter_designation, '')
  and d.source = 'seed';

insert into chapter_directory (
  org_letters, org_name, archetype, chapter_designation, university,
  university_short, founded_year, default_colors, website, source
)
select
  s.org_letters, s.org_name, s.archetype, s.chapter_designation, s.university,
  s.university_short, s.founded_year, s.default_colors, s.website, s.source
from _seed_chapter_directory s
where not exists (
  select 1
  from chapter_directory d
  where d.org_letters = s.org_letters
    and d.university  = s.university
    and coalesce(d.chapter_designation, '') = coalesce(s.chapter_designation, '')
);

do $$
declare
  total int;
begin
  select count(*) into total from chapter_directory;
  raise notice 'chapter_directory: % rows after load (% in seed)', total, 50;
end $$;

-- The loader relies on `on commit drop`; a migration runs inside `db push`'s
-- transaction, and the PGlite replay runs every migration and then the loader
-- itself in one session, where a lingering temp table would collide with the
-- loader's own. Drop it explicitly so both paths see a clean session.
drop table _seed_chapter_directory;

